### ISSUE TITLE
On autocomplete fail callback

### ISSUE THREAD

**Issue by cburbank** [kenny-hibino/react-places-autocomplete#10]
@kenny-hibino 

It could be useful to allow users to pass in a callback to execute when `PlacesServiceStatus` is not `OK` (i.e., no predictions were found). Currently it writes an error message to the console.

Along those same lines - when autocomplete fails, the current predictions aren't cleared so the autocomplete items remain visible. Do you think it would make sense to give the option of clearing the autocomplete items on fail? It could be a boolean prop, maybe `clearItemsOnFail` or something like that.

If this sounds good to you I'd be happy to do it and open a PR.

Thanks!

**Comment by kenny-hibino** [comment]
Currently the library doesn't have a great support for error handling. I think your suggestion make a lot of sense. 

If I was a user of this library, ideally the library has a sensible default for error handling and allow user to plug in their own error handling function. It'd be great if you can work on this, and we can see it in a feature branch! Let me know if you have more suggestion on this issue or any other things in the library. 

Thanks Chris!

**Comment by kenny-hibino** [comment]
Closing this thanks to @cburbank #12
