### ISSUE TITLE
google's getPlacePredictions doesn't cope with options as illustrated in the props doc

### ISSUE THREAD

**Issue by diligiant** [kenny-hibino/react-places-autocomplete#102]
In the documentation, you suggest
```
const options = {
  location: new google.maps.LatLng(-34, 151),
  radius: 2000,
  types: ['address']
}

<PlacesAutocomplete
  inputProps={inputProps}
  options={options}
/>
```

but this leads getPlacePredictions to return `INVALID_REQUEST` as [documentation](https://developers.google.com/maps/documentation/javascript/places-autocomplete#place_autocomplete_service) shows that the call should have an prod field and an options prop.

This was working before but I guess google's api is more strict now. I was able to overcome the problem by now defining
```
const options = {
  options: {
    location: new google.maps.LatLng(-34, 151),
    radius: 2000,
    types: ['address']
  }
}
```
but I guess [PlacesAutocomplete.js#L67](https://github.com/kenny-hibino/react-places-autocomplete/blob/master/src/PlacesAutocomplete.js#L67) might just need to be `options: this.props.options`

**Comment by kenny-hibino** [comment]
@diligiant Thank you for reporting! Would you mind checking your `google.maps.version`?

**Comment by diligiant** [comment]
3.29.14

**Comment by kenny-hibino** [comment]
I'm using the exact same version in the demo. The `options` props seem to be working fine there, would you mind double checking the keys of options?

**Comment by diligiant** [comment]
I did before! Which example are you talking about? (in `https://kenny-hibino.github.io/react-places-autocomplete/` options is `{}`)

**Comment by kenny-hibino** [comment]
I just added options locally and could not reproduce the error.

**Comment by diligiant** [comment]
ok, diving in… ;(

**Comment by kenny-hibino** [comment]
You can try this snippet to test 

```js
const autocompleteService = new google.maps.places.AutocompleteService()
const response = autocompleteService.getPlacePredictions({
  input: 'San Francisco',
  location: new google.maps.LatLng(-34, 151),
  radius: 2000,
  types: ['address']
})
```

Try this in your console 👍

**Comment by diligiant** [comment]
so…
your example works just fine (btw, is `address` valid? I don't see it in [AutocompletionRequest](https://developers.google.com/maps/documentation/javascript/reference#AutocompletionRequest))

It works too if I replace address by `geocode` or `(cities)`. But if I replace it by both of them, it doesn't anymore (it used to).

What's really weird is that I did then modify the jsfiddle [here](https://developers.google.com/maps/documentation/javascript/examples/places-queryprediction) and it works 🤔

The pain is that the google API isn't debug-friendly with its minifying…

**Comment by kenny-hibino** [comment]
Okay, I'll keep this issue open for now, in case someone else encounter the same problem. In the meantime, please use the `options` that work for you 👍

**Comment by diligiant** [comment]
I'm gonna go to the bottom of this…

**Comment by diligiant** [comment]
Nevermind, it seems that Google fixed a lenient API…

**Comment by kenny-hibino** [comment]
@diligiant Thank you for taking a look at this 👍
