### ISSUE TITLE
Input should set autocomplete="off" by default

### ISSUE THREAD

**Issue by ericluwj** [kenny-hibino/react-places-autocomplete#104]
I am placing this input into a form with other inputs which I still intend to have the autocompletion function, so I can't turn off autocompletion for the whole form.
How to set the input attribute `autocomplete` to `off`?
Doesn't it make sense also for this input box to automatically disable autocompletion?

**Comment by kenny-hibino** [comment]
@ericluwj You can pass any arbitrary props to the input element through `inputProps`. 
I think the following is what you want

```js
const inputProps = {
  onChange: this.handleChange,
  value: this.state.address,
  autocomplete: 'off',
}

// And in render method
<PlacesAutocomplete inputProps={inputProps} />
```

Would this work for you?

**Comment by ericluwj** [comment]
@kenny-hibino Thanks, this would work. I did not realize `inputProps` actually contains flexible props for the input field.
However since the browser's autocompletion widget would clash with this autocompletion widget, should not the `autoCompletion` attribute be disabled by default?

**Comment by kenny-hibino** [comment]
@ericluwj Could you explain or submit a code snippet where this would be an issue?

**Comment by ericluwj** [comment]
![untitled-1](https://user-images.githubusercontent.com/1736023/29056573-6a048318-7c36-11e7-8077-84d4c62db01d.jpg)
This is what will happen if the input field coincidentally activates browser autocompletion as well.

**Comment by kenny-hibino** [comment]
Ahh I see. I will add that default 👍

**Comment by FbPalmabit** [comment]
@kenny-hibino this doesn't work for me
`const inputProps = {
  onChange: this.handleChange,
  value: this.state.address,
  autocomplete: 'off',
}
 `

**Comment by ericluwj** [comment]
It should be:
```
const inputProps = {
  onChange: this.handleChange,
  value: this.state.address,
  autoComplete: 'off'
}
```

Note it is `autoComplete`, not `autocomplete`.

**Comment by lauterry** [comment]
```autoComplete: 'off'``` doesn't work for me but ```autoComplete: 'disabled'``` does

**Comment by racheldelman** [comment]
@lauterry Thanks! That fixed it for me. @kenny-hibino can the default be switched to `disabled` instead of `off`?
