### ISSUE TITLE
Allow autoFocus prop for input

### ISSUE THREAD

**Issue by mull** [kenny-hibino/react-places-autocomplete#11]
Allow an `autoFocus` prop that is sent down to the <input> element. Useful for pages when the component is the main function.

Thanks for the great component!

**Comment by kenny-hibino** [comment]
@mull thanks for making this issue! It makes sense to have `autoFocus` as a prop. I'll work on that 👍

**Comment by Pegahkeshavarz** [comment]
is this working? i cant create it and i am using the lastest
