### ISSUE TITLE
Change react dependency to peer dependency

### ISSUE THREAD

**Issue by dummerbd** [kenny-hibino/react-places-autocomplete#113]
Most react packages put react in the `peerDependencies` section of the `package.json`. I'm not expert on npm but to my understanding this avoids multiple copies of react being placed in the dependency tree. I noticed my build size increased more than I expected after installing this so I dug around and found that changing your `package.json` removed an extra copy of react.

**Comment by kenny-hibino** [comment]
@dummerbd Thank you for creating this issue! You are definitely right, I'll make that change 👍
