### ISSUE TITLE
Css with styled-components

### ISSUE THREAD

**Issue by TylerL-uxai** [kenny-hibino/react-places-autocomplete#117]
Don't know why they did this, because it's made it impossible for me to set a simple css style for 2 days... but react-boilerplate ( https://github.com/react-boilerplate/react-boilerplate ) uses a module called styled-components. Any idea how to make the SimpleForm work with styled-components?

**Comment by j** [comment]
@TylerL-uxai the only way I got by was to add a wrapper and set the classNames manually.

```javascript
const SearchWrapper = styled.div`
  .search-input {
    width: 100%;
    height: 30px;
  }

  .search-autocomplete-container {
    border-bottom: honeydew;
    border-left: honeydew;
    border-right: honeydew;
    border-top: 1px solid #e6e6e6;
    box-shadow: 0 2px 4px rgba(0,0,0,0.2);
    border-radius: 0 0 2px 2px;
  }
`;

// ...

renderAutocomplete = ({ input, custom }) => (
  <PlacesAutocomplete
    inputProps={{ ...input, ...custom }}
    classNames={{
      input: 'search-input',
      autocompleteContainer: 'search-autocomplete-container',
    }}
    options={{ types: ['geocode'] }}
    onSelect={this.onSelectLocation}
    autocompleteItem={({ formattedSuggestion }) => (
      <Suggestion>
        <PlaceIconStyled size="17px" />
        <MainText>{formattedSuggestion.mainText}</MainText>
        <SecondaryText>{formattedSuggestion.secondaryText}</SecondaryText>
      </Suggestion>
    )}
  />
);

render() {
  return (
    <SearchWrapper>
      {this.renderAutocomplete()}
    </SearchWrapper>
  )
}

```

These are snippets of what I had to do.  Felt nasty but works.  I'm using styled-components & redux-form.

**Comment by TylerL-uxai** [comment]
Omg, thank you so much for all the effort you put in to this! Can I PM you about my project? It's very simple and maybe we can work together to finish it.

**Comment by TylerL-uxai** [comment]
I'm getting this.autocomplete is not a function when I add parenthesis.
`
{this.renderAutocomplete}`

Eliminates the error but it won't render, even if I do the following

```
  renderAutocomplete = () => (
    <PlacesAutocomplete inputProps = {inputProps}
    />
  );
```

**Comment by kenny-hibino** [comment]
@TylerL-uxai Is the library incompatible with Styled-Component library?

**Comment by egeriis** [comment]
@kenny-hibino Is not "incompatible" because styled-components is so flexible. There would be enhanced compatibility however, if `className` could be set on `PlacesAutocomplete`. Would allow developers to do:

```js
import PlacesAutocomplete from 'react-places-autocomplete';
const StyledAutocomplete = styled(PlacesAutocomplete)`
  border: 1px solid red;
`;
```

**Comment by kenny-hibino** [comment]
Definitely need this enhancement. Will work on this soon 👍

**Comment by egeriis** [comment]
What I've done for now:

```js
import styled from 'styled-components';

export const classNames = {
  root: 'root',
  input: 'input',
  autocompleteContainer: 'autocomplete-container',
  autocompleteItem: 'autocomplete-item',
  autocompleteItemActive: 'autocomplete-item-active'
};

export default styled.div`
  .${classNames.root} {
    //
  }

  .${classNames.input} {
    //
  }

  .${classNames.autocompleteContainer} {
    //
  }

  .${classNames.autocompleteItem} {
    //
  }

  .${classNames.autocompleteItemActive} {
    //
  }
`;
```

Ideally this would be the method:

```js
export default styled(PlacedAutocomplete)`
  .input {}
  .autocompleteContainer {}
  .autocompleteItem {}
  .autocompleteItemActive {}
`;
```

**Comment by irvingv8** [comment]
Hello there! I was looking into this and as the suggestion from @egeriis would totally work, I decided to solve this issue making use of HOC this is the way I solved it (if feeling like this could be useful in the docs, let me know and I can make a PR):


*Removed unrelated code because I'm using redux form on top on this
```javascript
// Component to be exported (notice how "inputClass" and "autocompleteClass"
// are coming from props)
const PlaceInput = props => {
  return (
    <PlacesAutocomplete
      classNames={{
        input: props.inputClass,
        autocompleteContainer: props.autocompleteClass
      }}
    />
  );
};

// HOC to assign the styles for the input element
const inputStyles = Component => styled(
  ({ className: inputClass, ...props }) => (
    <Component {...props} inputClass={inputClass} />
  )
)`Your Styles for the input element here`;

// HOC to assign the styles for the autocompleteContainer element
const suggestionStyles = Component => styled(
  ({ className: autocompleteClass, ...props }) => (
    <Component {...props} autocompleteClass={autocompleteClass} />
  )
)` Your Styles for the autocompleteContainer element here`;

// Apply both HOCs when exporting
export default suggestionStyles(inputStyles(PlaceInput));
```

You could possibly enhance this even more to avoid some repetition, but this will get you working.

**Comment by kenny-hibino** [comment]
We introduced render prop in v.7.x so that user of the library has a full control over rendering. Hopefully this will solve this issue with integrating with other libraries like styled-components 👍 

Please give a v.7 a try and any feedback will be appreciated!!
