### ISSUE TITLE
Cannot scroll suggestion on mobile

### ISSUE THREAD

**Issue by lauterry** [kenny-hibino/react-places-autocomplete#118]
Hello

When the list of suggestion appears on a mobile device, users tends to scroll to look for their address in the list of address suggestion.

However, when the user scrolls by putting their fingers on the suggestions area, an address is selected and the list of suggestions disappear.

Here is a hint for a possible solution :  https://stackoverflow.com/a/32120668

Best regards

**Comment by lauterry** [comment]
Hello

I haven't got any feedback on this issue yet.

I want just to make sure that you have understood my point. If not, I'll try to re explain.

Best regards

**Comment by kenny-hibino** [comment]
@lauterry Thank you for reporting. Would you mind explaining in detail? It would be helpful if you could provide the current behavior and expected behavior of the component 👍

**Comment by lauterry** [comment]
Hi @kenny-hibino 

In order to reproduce the issue, please open https://kenny-hibino.github.io/react-places-autocomplete on a mobile phone.

1. Click on the input
2. The virtual keyboard appears
3. Enter an address
4. Suggestions appears but remains invisible due to the virtual keyboard
5. The natural behavior is to scroll the page to view all the suggestions. However, if you scroll by putting the finger on the suggestions area, the component acts if you have selected a suggestion.

Actual behavior : 
The suggestions list disappears and a suggestion is selected

Expected behavior : 
The suggestions list remains on screen, no suggestion is selected and the user can scroll down the page even if he touched the suggestion list.

I hope that its clear. If not, let me know please

Thanks !!

**Comment by kenny-hibino** [comment]
I see, this needs to be fixed for a better mobile experience. Thank you for reporting this @lauterry ! PR is always welcome 👍

**Comment by ktusharprdxn** [comment]
Hi @kenny-hibino, any luck in fixing this issue??

**Comment by KevinRobichon** [comment]
@ktusharprdxn my fork should fix the issue
@kenny-hibino could we merge my changes into the project ?

**Comment by ktusharprdxn** [comment]
@kenny-hibino @KevinRobichon Any Idea when this changes will get merged in master? as this is important for my project. Also there should be option for restricting suggestions for particular locations like US only or UK or india.

**Comment by ThunderDev1** [comment]
@KevinRobichon thanks for resolving the issue, however I can't seem to use your fork. I tried `npm install KevinRobichon/react-places-autocomplete` but the resulting folder only contains 3 files

![image](https://user-images.githubusercontent.com/7251011/33999485-e1908058-e0ea-11e7-9fe9-64538560b5a7.png)
Not sure what I'm doing wrong

**Comment by brendonlamb** [comment]
Any updates on this? Just finding this bug on my app as well

**Comment by KevinRobichon** [comment]
@ThunderDev1 you can use the branch #dist-in which contains dist/ folder built with my changes. Don't forget to clean the npm or yarn cache before installing

**Comment by chrisrichard** [comment]
I need this too.

**Comment by kenny-hibino** [comment]
@KevinRobichon Sorry for not reviewing PR for so long. Left comments in the PR 👍
