### ISSUE TITLE
Using with next.js

### ISSUE THREAD

**Issue by yunyu** [kenny-hibino/react-places-autocomplete#119]
I'm not really sure where to report this issue, but basically, the inclusion of Google image imports makes this very difficult to use with next.js (SSR).

When I follow the instructions, I end up getting

```
Uncaught Error: Module parse failed: node_modules\react-places-autocomplete\dist\images\powered_by_google_default.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```

Would you happen to know anything about how to resolve this? All of the existing answers that I've seen involve handling images on project code, not external components.

(I personally think that the images shouldn't really be shipped in the library and should be passed in as a prop or included as inline SVGs instead for retina support, but that's another issue.)

**Comment by kenny-hibino** [comment]
@yunyu Thank you for opening this issue!
I like the idea of moving the option to add Google image to a prop. It might be more useful to add an optional `footer` prop, where the user of the library can provide a simple functional component to customize dropdown footer.

**Comment by jth0024** [comment]
I really like this idea. It would solve some issues for me as well.

**Comment by Goluis** [comment]
For the people trying to make the package work with next you have two options:

Stay in the version 5.3.1 or install the package [file-loader](https://www.npmjs.com/package/file-loader) (or one similar) and then add the following code to your `next.config.js` file

```js
module.exports = {
  webpack: config => {
    config.module.rules.push({
      test: /\.(png|jpg|gif)$/,
      use: [
        {
          loader: 'file-loader',
          options: {}
        }
      ]
    })

    return config
  }
}
```

**Comment by jameskennethrobinson** [comment]
@Goluis Thank you!

**Comment by kaizenberg** [comment]
@Goluis Thanks!

**Comment by JonAbrams** [comment]
@Goluis Your solution worked for me in dev mode, but once deployed to prod the image isn't there. Got any hints?

**Comment by Goluis** [comment]
@JonAbrams is it happening in both SSR and client or only in one o those ?
are there any errors ?

**Comment by JonAbrams** [comment]
Seems to be both.

<img width="700" alt="pasted_image_10_24_17__9_16_pm" src="https://user-images.githubusercontent.com/1243092/31980361-cc9c706a-b900-11e7-841f-229f4ecfb265.png">

I tried setting the following on `file-loader` to no avail:
```
options: {
  useRelativePath: process.env.NODE_ENV === 'production'
}
```

I assume you've had no issues?

**Comment by Goluis** [comment]
I'm not getting any error, if you can share a repo it will be good

**Comment by jonathanphz** [comment]
Having same problem - don't have a `next.config.js` file and using react-places-autocomplete 5.3.1 still shows a warning.

**Comment by kaizenberg** [comment]
@JonAbrams, I have the same problem. Did you fix your problem?

**Comment by JonAbrams** [comment]
@kaizenberg Unfortunately I haven't had the time to investigate further, so am still having the issue. Just hoping that Google doesn't cut us off for now.

**Comment by Goluis** [comment]
Update: to work with a newer version than `5.3.1` using Next is probably not possible (I actually don't have any production issues, but I don't know if the image is actually doing something)

to see why here's an issue: https://github.com/zeit/next.js/issues/1926

The solution would be something like this: https://github.com/zeit/next.js/issues/1245 - But is not yet implemented

**Comment by JonAbrams** [comment]
@goluis Is it possible to specify the image url as a prop? That way I can just put the google logo in the static directory.

**Comment by kenny-hibino** [comment]
This won't be an issue with v6.x or above 👍
