### ISSUE TITLE
Touch action on suggestion also triggers elements beneath

### ISSUE THREAD

**Issue by spykr** [kenny-hibino/react-places-autocomplete#123]
I'm having an issue on mobile where touching a suggested address will also trigger any clickable elements behind it.

You can test this on my web app: https://www.darcyglennen.com/routefinder/

Open Chrome, press "toggle device toolbar" in the dev tools to switch the viewport to a phone view with touch emulation. Type a random number in the 1st input box and click the address suggestion that is over the "Start from current location" checkbox. You'll see the checkbox is also clicked.

**Comment by kenny-hibino** [comment]
@spykr Thank you for submitting this issue! I followed your instruction and I see that touch event propagates to other elements. Seems to be a bug.  I'm guessing `event.stopPropagation` on touch event will fix this. PR is welcome!

**Comment by cscottsa** [comment]
Can we please merge this? @kenny-hibino

**Comment by joenot443** [comment]
I'm still getting this bug - can we consider merging the fix?

**Comment by brendonlamb** [comment]
while i'm confident @spykr  's solution would work as well, I noticed i'm having similar issues with another library. Currently a simple solution to this is to just install **react-fastclick**

https://github.com/JakeSidSmith/react-fastclick

Cheers!

**Comment by kenny-hibino** [comment]
Fixed via ef4dc46
