### ISSUE TITLE
geocodeByAddress undefined lat,lng

### ISSUE THREAD

**Issue by niiapa** [kenny-hibino/react-places-autocomplete#125]
In the function: 
`geocodeByAddress('Tokyo, Japan')
.then(results => getLatLng(results[0]))
.then(({ lat, lng }) => console.log('Successfully got latitude and longitude', { lat, lng }))
`
the second thennable creates an error because it says it's trying to retrieve the lat and lng of an undefined object. I've tried it multiple ways, it doesn't work. Thanks.

**Comment by kenny-hibino** [comment]
I see. This needs to be fixed. Thank you for reporting @niiapa !

**Comment by niiapa** [comment]
Turns out it's just a typo in the readme. The .then function should be on the `getLatLng` function. The found the snippet at the bottom of the repo page. Thanks.
