### ISSUE TITLE
Error ZERO_RESULTS when autocomplete

### ISSUE THREAD

**Issue by kaizenberg** [kenny-hibino/react-places-autocomplete#133]
Hi everyone!

I have a doubt, when I search a place that not exist, I get this console error:

`[react-places-autocomplete]: error happened when fetching data from Google Maps API. Please check the docs here (https://developers.google.com/maps/documentation/javascript/places#place_details_responses)
Status:  ZERO_RESULTS`

Here there an image to show you:
<img width="1272" alt="screen shot 2017-10-19 at 4 47 12 pm" src="https://user-images.githubusercontent.com/3875593/31790928-6c92044e-b4ed-11e7-9c00-0f94d4a6c1ce.png">

Note: in the [example of the library](https://kenny-hibino.github.io/react-places-autocomplete/) too show it, such as I show above.

How can I control it?

Thank you!

**Comment by JonatanSCS** [comment]
There are [`onError`](https://github.com/kenny-hibino/react-places-autocomplete#onError) and [clearItemsOnError](https://github.com/kenny-hibino/react-places-autocomplete#clearitemsonerror) handle error Optionals Props.

You need something like:

```
<PlacesAutocomplete onError={this._handleError} clearItemsOnError={true} inputProps={mailingAddressProps} />
```

**Comment by kaizenberg** [comment]
@JonatanSCS Thanks!

**Comment by theodoregold** [comment]
You should at least mention this in the example. This isn't really an "error". Google API is returning status 200 with empty array. Which is totally fine and expected. There is no need to create an error or blast the console.

**Comment by vladcom** [comment]
THANK YOU!!!!
