### ISSUE TITLE
How do I use 2 <PlaceAutocomplete> fields in the same form? (Question)

### ISSUE THREAD

**Issue by roybigapps** [kenny-hibino/react-places-autocomplete#140]
Hello,
this is not an issue but a question: I have a react form and I need to have 2 addresses field with google autocomplete address. I am using this great extension and with 1 field, the example given is working great but when I try to add another field, It fails. they are overwrite each other. I change and gave a deferent name for the value and 2 declaration:
`this.onChange = (newOrigin) => this.setState({ newOrigin })`
`this.onChange = (newDestination) => this.setState({ newDestination })`
Please help.

**Comment by Hatzl** [comment]
Hello,

what was your solution?
