### ISSUE TITLE
ability to save and include original input value when iterating over autocomplete entries

### ISSUE THREAD

**Issue by markph1990** [kenny-hibino/react-places-autocomplete#141]
I was thinking about adding ability to save input's value when no entry is selected.
I type some phrase, for example 'Berl' and I'm about to select any of the entries from autocomplete (via arrows) which would change input's value. While doing that, previous/original value is saved (in local state) to be retrieved later, for example to being included as one of autocomplete entries. Attached gif should describe it more precisely.
![peek 2017-12-08 23-41](https://user-images.githubusercontent.com/10480596/33788467-c0a35522-dc72-11e7-93a5-33eb757c2b9e.gif)

I can send PR if such functionality is acceptable.

**Comment by kenny-hibino** [comment]
@markph1990 Yes, this looks like the behavior in Google Maps. Let's add this ability 👍 

Thank you for submitting this issue!
