### ISSUE TITLE
how to restrict bounds in options ?

### ISSUE THREAD

**Issue by arnaudambro** [kenny-hibino/react-places-autocomplete#143]
I tried many stuff, and my last shot (not working) is the following :

    const options =  {
      location: new google.maps.LatLng(48.853, 2.35),
      radius: 200000,
      types: ['geocode', 'establishment'],
      bounds: new google.maps.LatLngBounds(google.maps.LatLng(48.8527, 2.3407), google.maps.LatLng(48.8533, 2.3503)),
      rankBy: google.maps.places.RankBy.DISTANCE,
      strictbounds: true
    }`

how can you do ?

**Comment by rstormsf** [comment]
it doesn't looks like he exposes `setBounds` function which you can limit the location search

**Comment by arnaudambro** [comment]
Sorry I didn't understand your point: you're saying that the `bounds` option doesn't exist ?

**Comment by Th3Mouk** [comment]
@kenny-hibino hi ! Can u please help us ? It seems pretty easy but I don't know how to do.

The query should look like this: `https://maps.googleapis.com/maps/api/place/autocomplete/xml?input=Amoeba&types=establishment&location=37.76999,-122.44696&radius=500&strictbounds&key=YOUR_API_KEY`

Probably just a PropType to add ?

**Comment by kenny-hibino** [comment]
Sorry for a late reply. I need to investigate this further

**Comment by Th3Mouk** [comment]
I've investigated, it seems this functionality is not implemented on the autocomplete service library yet. They're is a task on google tracker somewhere.

With API call : https://developers.google.com/places/web-service/autocomplete
There is an implementation of strictBounds

But no on the current AutocompletService: https://developers.google.com/maps/documentation/javascript/reference#AutocompleteService

The solution is to call the HTTP service where this option is deployed.

Or just wait for the next release of the autocomplete service: https://developers.google.com/maps/documentation/javascript/3.exp/reference

**Comment by kenny-hibino** [comment]
@Th3Mouk Thank you for investigation this! Closing this issue for now.

**Comment by bplmp** [comment]
I'm using Google Maps API v3.32.8, but the `strictBounds` option still doesn't seem to work.

    const placesAutocompleteOptions = {
      location: new google.maps.LatLng(GLOBALS.city_center.lat, GLOBALS.city_center.lon),
      radius: 20000,
      types: ['address'],
      componentRestrictions: {country: "br"},
      bounds: new google.maps.LatLngBounds(
        new google.maps.LatLng(GLOBALS.city_bbox_s, GLOBALS.city_bbox_w),
        new google.maps.LatLng(GLOBALS.city_bbox_n, GLOBALS.city_bbox_e)
      ),
      strictBounds: true
    };

Any ideas why?

**Comment by con322** [comment]
@bplmp did you ever get the bounds to work?

**Comment by bplmp** [comment]
@con322 nope, unfortunately.

I noticed that it does bias the results towards the bounds, so it is interpreting the bounds correctly, but it doesn't _restrict_ to matches inside the bounds, so still no `strictBounds`.

**Comment by theasteve** [comment]
> it doesn't look like he exposes `setBounds` function which you can limit the location search

this is not true for the `AutocompleteService`. Since this class doesn't have an strict bounds option.
