### ISSUE TITLE
Could geocodeByAddress return the whole result?

### ISSUE THREAD

**Issue by mangakid** [kenny-hibino/react-places-autocomplete#15]
It would be useful to have the whole object available :)

**Comment by nehabo** [comment]
I used google.maps.Geocoder API to get the address from the location coordinates. 

```
onSelect(address) {
    this.props.onSelect(address);
    this.setState({ loading: true }); 
    geocodeByAddress(address,  (err, { lat, lng }) => {
      if (err) {
        console.log("Oh no!", err);
        this.setState({
          geocodeResults: this.geocodeFailure(err),
          loading: false,
        });
      }
      console.log('Yay! got latitude and longitude for ${address}', { lat, lng });
      this.setState({
        geocodeResults: this.geocodeSuccess(lat, lng),
        loading: false,
      });
    });

  }

geocodeSuccess(lat, lng) {
    // updates location in state
    this.props.geocodeSuccess(lat, lng);

    // gets formatted address to populate form fields
    const geocoder = new google.maps.Geocoder();
    geocoder.geocode({ 'location': { lat, lng } }, (results, status) => {
      if (status === 'OK') {
        if (results[0]) {
          console.log(results[0].formatted_address);
          this.setState({
            reverseGeocodeResults: this.reverseGeocodeSuccess(results),
          });
        } else {
          console.log('No results found');
        }
      } else {
        console.log('Geocoder failed due to: ' + status);
      }
      return results[0];
    });
  }
  reverseGeocodeSuccess(results) {
    this.props.getAddress(results);
  }

geocodeFailure(err) {
    console.log('Not able to get location', err);
  }

```

**Comment by cburbank** [comment]
@mangakid  I agree that would be useful. The extra call to `google.maps.Geocoder()` in @nehabo's example wouldn't be necessary if `geocodeByAddress` was returning the full result in the first place.

**Comment by kenny-hibino** [comment]
@mangakid Thank you for creating this issue! 
Let's work on this and include it in the future release 👍

**Comment by alveshelio** [comment]
Hi @nehabo,

I'm new to React, and I'm playing with the code example and it works fine, however, I'd like to add your code but I'm not sure where to place it. Could you please help me with some instructions where to place this code? Should I place it inside the function handleFormSubmit that is called when we submit the form? 

Thank you

**Comment by alveshelio** [comment]
Hi @kenny-hibino, when do you think this code will be implemented in a new version? Thank you very much for the great work.

**Comment by kenny-hibino** [comment]
@alveshelio I will work on it this weekend, and have it shipped by the start of next week 👍

**Comment by kenny-hibino** [comment]
@mangakid The main purpose of `geocodeByAddress` helper function is to extract `latitude` and `longitude` from the API payload. But I think we can have the callback function take the third argument and pass the entire payload. 

So the function signature and usage could look like this

```javascript
const address = 'New York, NY'
gecodeByAddress(address, (err, { lat, lng }, results) => {
  if (err) { return; }

  console.log(`Yay, got lat and lng for ${address}`, { lat, lng });
  console.log('Also, the whole API payload!', results);
});
```

Would that be helpful?

**Comment by alveshelio** [comment]
Hi @kenny-hibino, you really rock :) 
Can I pay you a beer or a coffee? :)

**Comment by kenny-hibino** [comment]
@alveshelio thanks! Just starting ⭐️ this project is enough for me!

**Comment by mangakid** [comment]
Hi @kenny-hibino, yes that would be great. Thanks.
