### ISSUE TITLE
'google' is not defined error when using new google.maps.LatLng

### ISSUE THREAD

**Issue by Engineering-Robert** [kenny-hibino/react-places-autocomplete#150]
When trying to set the options for the component, I run into the error:

`'google' is not defined  no-undef`

Here is what my options props looks like for the `PlacesAutocomplete` component:
```
options={{ 
  location: new google.maps.LatLng(44.2312, -76.4860),
  radius: 20000,
  type: ['address']
}}
```

I've got the script tag for the Google API in my index.html file and everything else works properly, but I cannot create access the google.maps object from the API for some reason.

Any help would be appreciated!

**Comment by Engineering-Robert** [comment]
I solved this by adding the following to the top of my component to tell my React app that the `google` name will be available globally on run time:

`/*global google*/`

Solved it thanks to [this comment](https://github.com/kenny-hibino/react-places-autocomplete/issues/57#issuecomment-335043874).

**Comment by johnilizy17** [comment]
how did you put it global google because am confused on how to apply it
