### ISSUE TITLE
Ability to style input when autocompleteContainer is open

### ISSUE THREAD

**Issue by antoniobrandao** [kenny-hibino/react-places-autocomplete#158]
I don't seem to find an option that would allow me to apply a specific style to the `input` when the results container is open.

What I am trying to achieve, is, having styled my input with rounded corners, I would like the bottom-left and bottom-right corners to become flat when opening the results container.

Is this option absent or am I missing something?

**Comment by kenny-hibino** [comment]
@antoniobrandao Thank you for submitting this issue! 
You're correct, this option is absent. Sounds like a useful feature. I'll add this to the feature list 👍

**Comment by kenny-hibino** [comment]
Hopefully render props in v.7.x will solve your issue @antoniobrandao! Any feedback will be very appreciated!! Closing this issue 👍
