### ISSUE TITLE
react-google-autocomplete not working on page refresh

### ISSUE THREAD

**Issue by KarthickRaja3018** [kenny-hibino/react-places-autocomplete#161]
I am loading google service inside the script tag
 <Script
            url="https://maps.googleapis.com/maps/api/js?key=key&libraries=geometry,drawing,places"
        />

for the first time its working fine when I refresh the page its not working throwing error as google map must be loaded

**Comment by galto4ir** [comment]
It's just api limit, try again tomorrow or create your own api
