### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by mollynordh** [kenny-hibino/react-places-autocomplete#166]
Any way to only get result in a specific language? I'd like to get my list of places in Swedish rather than English. Is there any way to do that?

**Comment by jhalborg** [comment]
@mollynordh - Why did you close this, did you find a way? If so, can you please share? :)

**Comment by Rasha-Dj** [comment]
@jhalborg :+1: 
@mollynordh Have you found solution for this?

**Comment by tpkemme** [comment]
@jhalborg @mollynordh 

The only way i could find to achieve a different language is to include a language param in your google maps script:

`<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places&language=fr"></script>`

Hope this helps.  It would be really great if language was an option you could pass to the component.

**Comment by damdafayton** [comment]
Hi, why this issue is closed? Is language option feature working?
