### ISSUE TITLE
classNames and styles properties don't work

### ISSUE THREAD

**Issue by ManuelJF** [kenny-hibino/react-places-autocomplete#173]
i want to overwrite the inline styles for the component, but when pass a object with my custom styles don't change my styles and the same case is when i pass a object with custom classNames does not work.

![captura de pantalla 2018-02-15 a la s 10 04 54 a m](https://user-images.githubusercontent.com/15016968/36266715-c57bdfb0-1237-11e8-8e1c-88e7278c59f8.png)

![captura de pantalla 2018-02-15 a la s 10 05 14 a m](https://user-images.githubusercontent.com/15016968/36266726-cab59ee4-1237-11e8-807a-eff2cdca9a08.png)

**Comment by kenny-hibino** [comment]
v.7.x will accept render prop via `children` so hopefully this won't be a problem!
