### ISSUE TITLE
Typing into the PlacesAutocomplete field clears all other fields in the same form

### ISSUE THREAD

**Issue by ajien** [kenny-hibino/react-places-autocomplete#182]
**Do you want to request a *feature* or report a *bug*?**
Bug/Question
**What is the current behavior?**
I have a form with multiple fields including one using PlacesAutocomplete. When typing into the autocomplete field, all other fields in the same form gets cleared.

Is this a bug? How do I prevent it from happening?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**

**Comment by kenny-hibino** [comment]
@ajien  I don't think this is a bug of the library. I'm closing this issue for now, but feel free to re-open if you the identified a bug in the library!
