### ISSUE TITLE
Add TypeScript Support

### ISSUE THREAD

**Issue by kenny-hibino** [kenny-hibino/react-places-autocomplete#186]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently the library doesn't support TypeScript 

**What is the expected behavior?**
Provide TypeScript support
- Add types

**Comment by guilhermehubner** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24259 :wink:

**Comment by kenny-hibino** [comment]
@guilhermehubner Awesome! So this library can be used in TypeScript without having type definitions provided by this library? (Sorry if I'm asking a noob question, I haven't tried out TypeScript yet!)

**Comment by guilhermehubner** [comment]
@kenny-hibino yeah! DefinitelyTypes is a oficial typings repository (the advantage to submit types definition to there instead maintain it on project is the Q&A, this repository is maintained by Microsoft team and require some best pratices).

Your lib will work with TypeScript just by add the definition with `yarn add @types/react-places-autocomplete`. :wink:

**Comment by kenny-hibino** [comment]
Great! Thanks for adding type definition @guilhermehubner 👍

**Comment by pixellos** [comment]
Hi, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24259 is incompatible with current version and some types are missing.
