### ISSUE TITLE
Focus with adding custom css

### ISSUE THREAD

**Issue by andreykishtov** [kenny-hibino/react-places-autocomplete#187]
I am trying to implement simple css changes to css and i can`t find how can i add focus or hover in styles object. I simply want to have an onhover change of color on border bottom

```javascript
const myStyles = {
  root: { position: 'relative', marginRight: '40px' },
  input: {
    width: '100%',
    outline: 'none',
    border: 'none',
    transition: 'all 0.2s ease-out',
    borderBottom: '1px solid #EBEBEB',
    ':focus': {
      background:'red',
      borderBottom: '5px solid red !important'
    }
  },
  autocompleteContainer: { backgroundColor: 'green' },
  autocompleteItem: { color: 'black' },
  autocompleteItemActive: { color: 'blue' }
};
```
thanks

**Comment by kenny-hibino** [comment]
@andreykishtov We released v7 with render prop so that user of the library has a full control over the rendering. Please give it a try and this hopefully solves your issue!

Any feedback will be appreciated!
