### ISSUE TITLE
How to handle loading google for test with enzyme / jest

### ISSUE THREAD

**Issue by thetwosents** [kenny-hibino/react-places-autocomplete#189]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Throws error "Google Maps JavaScript API library must be loaded" when running npm run test. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

create-react-app, setup react-places-autocomplete then install enzyme and jest. run npm test and it will break.

**What is the expected behavior?**
Be able to run jest / enzyme without breaking app 

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**
Chrome,Mac, RPA6.1.3

**Comment by kenny-hibino** [comment]
@thetwosents Thank you for opening this issue. 
Because `PlacesAutocomplete` component has a dependency on Google Maps Places library it has to be available under the window object. 
One way to get around this is to mock `window.google` object in your test.
Example: 

```js
const setupGoogleMock = () => {
  /*** Mock Google Maps JavaScript API ***/
  const google = {
    maps: {
      places: {
        AutocompleteService: () => {},
        PlacesServiceStatus: {
          INVALID_REQUEST: 'INVALID_REQUEST',
          NOT_FOUND: 'NOT_FOUND',
          OK: 'OK',
          OVER_QUERY_LIMIT: 'OVER_QUERY_LIMIT',
          REQUEST_DENIED: 'REQUEST_DENIED',
          UNKNOWN_ERROR: 'UNKNOWN_ERROR',
          ZERO_RESULTS: 'ZERO_RESULTS',
        },
      },
      Geocoder: () => {},
      GeocoderStatus: {
        ERROR: 'ERROR',
        INVALID_REQUEST: 'INVALID_REQUEST',
        OK: 'OK',
        OVER_QUERY_LIMIT: 'OVER_QUERY_LIMIT',
        REQUEST_DENIED: 'REQUEST_DENIED',
        UNKNOWN_ERROR: 'UNKNOWN_ERROR',
        ZERO_RESULTS: 'ZERO_RESULTS',
      },
    },
  };
  global.window.google = google;
};

// in test file.
beforeAll(() => {
  setupGoogleMock();
});
```

Hope this helps!

**Comment by con322** [comment]
Thanks for providing the above setup, however I get the following erro:

TypeError: window.google.maps.Geocoder is not a constructor

Any ideas on how to fix?

**Comment by chiamtc** [comment]
@con322  I had the same problem before. `window.google.maps.Geocoder` is a class so just put `Geocoder:class{},`.
If you are using function in google map classes, e.g:
`fitBounds()` under `window.google.maps.Map` class:
Just  `Map:class{ setTilt(){} fitBounds(){}},`

Here's my google map classes mock under setupTests.js
```
window.google ={
    maps:{
        Marker:class{},
        Map:class{ setTilt(){} fitBounds(){}},
        LatLngBounds:class{},
        places:{
            Autocomplete: class {},
            AutocompleteService:class{},
            PlacesServiceStatus: {
                INVALID_REQUEST: 'INVALID_REQUEST',
                NOT_FOUND: 'NOT_FOUND',
                OK: 'OK',
                OVER_QUERY_LIMIT: 'OVER_QUERY_LIMIT',
                REQUEST_DENIED: 'REQUEST_DENIED',
                UNKNOWN_ERROR: 'UNKNOWN_ERROR',
                ZERO_RESULTS: 'ZERO_RESULTS',
            },
            PlacesAutocomplete:{
                INVALID_REQUEST: 'INVALID_REQUEST',
                NOT_FOUND: 'NOT_FOUND',
                OK: 'OK',
                OVER_QUERY_LIMIT: 'OVER_QUERY_LIMIT',
                REQUEST_DENIED: 'REQUEST_DENIED',
                UNKNOWN_ERROR: 'UNKNOWN_ERROR',
                ZERO_RESULTS: 'ZERO_RESULTS',
            }
        },

        MarkerClusterer:class{},
        Geocoder:class{},
    }
};
```

**Comment by tim-rohrer** [comment]
As a newbie, I appreciate this thread, but I continue to bang my head against the wall.

In my case, I'm trying to mock `PlacesService.getDetails`. Adding `PlacesService: class {}` resolves constructor issue, but leaves me with `getDetails` being undefined.

**Comment by OscarBarrett** [comment]
I prefer to mock the library instead. Simple example:

```tsx
interface Props {
  children: Function;
}

jest.mock('react-places-autocomplete', () => {
  const React = require('react'); // eslint-disable-line
  class PlacesAutocomplete extends React.Component<Props> {
    renderProps = {
      getInputProps: jest.fn(({ placeholder, className }) => ({ placeholder, className })),
      suggestions: [],
      getSuggestionItemProps: jest.fn(),
    };

    render() {
      return <>{this.props.children(this.renderProps)}</>;
    }
  }

  return PlacesAutocomplete;
});
```

Then you can still test changes to props, changes from within the render function etc that you couldn't do with shallow rendering, but you don't need to worry about internal requirements like the google API.

**Comment by Buuntu** [comment]
Has the API changed from AutocompleteService to AutocompletionService?  I haven't been able to get this to work with cypress and was wondering if the API has changed.

**Comment by suvasishm** [comment]
I am using beta version of Maps Javascript API (to call reverse geocode) which returns [Promise](https://developers.google.com/maps/documentation/javascript/reference/geocoder#Geocoder.geocode). 

In order to mock `google.maps.Geocode` and `google.maps.Geocode.geocode(..)` I did the following in line with the [comment above](https://github.com/hibiken/react-places-autocomplete/issues/189#issuecomment-377770674).

```TypeScript
const setupGoogleMock = () => {
  window.google = {
    maps: {
      Geocoder: jest.fn().mockImplementation(() => {
        return {
          geocode: jest.fn().mockResolvedValue([
            {
              formatted_address: `State St, Chicago, IL 60602, USA`,
            },
          ]),
        };
      }),
    },
  };
};

test('reverseGeo', async () => {
  setupGoogleMock();
  expect(await reverseGeo({lat: 22.99, lng: 88.22})).toBe(`State St, Chicago, IL 60602, USA`);
});
```

It works for me to mock test the following snippets:
```
export const reverseGeo = async(latlng: google.maps.GeocoderRequest): Promise<string> => {
  const geocoder = new google.maps.Geocoder();
  const results: google.maps.GeocoderResult[] = await geocoder.geocode({ location: latlng,});
  if (results) {
    return result[0].formatted_address;
  }
}
```

**Comment by aghArdeshir** [comment]
In my case @OscarBarrett  's solution worked, with a small addition: `window.google = undefined`

So:
```tsx
interface Props {
  children: Function;
}

jest.mock('react-places-autocomplete', () => {
  const React = require('react'); // eslint-disable-line
  class PlacesAutocomplete extends React.Component<Props> {
    renderProps = {
      getInputProps: jest.fn(({ placeholder, className }) => ({
        placeholder,
        className
      })),
      suggestions: [],
      getSuggestionItemProps: jest.fn()
    };

    render() {
      return <>{this.props.children(this.renderProps)}</>;
    }
  }

  return PlacesAutocomplete;
});

window.google = undefined;
```

**Comment by dulcineapena1** [comment]
@suvasishm I follow your example, it seems to work, but when I check the "coverage", it seems the test did not cover too much...

**Comment by suvasishm** [comment]
> @suvasishm I follow your example, it seems to work, but when I check the "coverage", it seems the test did not cover too much... 

Well, the goal was to having a functional mock for the library API. Coverage would probably depend on what your code does with the mocked response.

**Comment by georgesh96** [comment]
I am still having issue with the mock, I am a newbee here with jest testing but I get an error of dispatch of null when I mock the useplaceservice I am trying to test getPredictions function

**Comment by paola-codes** [comment]
Bless @hibiken and @chiamtc  

You guys solved a problem I had for two days until I found your solutions and mixed them for my case. You are heroes! Thank you!

**Comment by nathan-ch** [comment]
Hi, thank you for the solution. I still have this error and i thinks others, related to `e` object :
`e.LatLng is not a constructor` 

I don't know where is `e` in google object so i don't know how to fix this, thanks !

**Comment by rsleyland** [comment]
This worked for me:

```
jest.mock('react-places-autocomplete', () => ({
    ...jest.requireActual('react-places-autocomplete'),
    getInputProps: jest.fn(({ placeholder, className }) => ({ placeholder, className })),
    suggestions: [],
    getSuggestionItemProps: jest.fn(),
}));
```

**Comment by elhajjj** [comment]
Google has an [official maps mocking library](https://github.com/googlemaps/js-jest-mocks) now, looks neat.
