### ISSUE TITLE
How to run this project.

### ISSUE THREAD

**Issue by anirugu** [kenny-hibino/react-places-autocomplete#190]
I have done npm installed but not sure how to run this project. Trying to find a thread in issue about this but didn't fine anything.

Let me know how to run this. I try command like yarn start, npm run dev which run the project in browser but it doesn't help.

I am using VS code for this, Thanks for this repos.

**Comment by kenny-hibino** [comment]
@anirugu Try `npm run demo` if you want to run the demo locally.
