### ISSUE TITLE
Get postal code

### ISSUE THREAD

**Issue by nishtacular** [kenny-hibino/react-places-autocomplete#192]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Returns address without postal_code

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Enter address in autocomplete field, does not return postal_code value along with the full address

**What is the expected behavior?**
Should also, return the the `address_components` field for the place so additional values can be extracted.

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**
^6.1.3

**Comment by Dashue** [comment]
I hit this as well, and then I realized that this lib doesn't make a call to the place api. Only the autocomplete api. You'll have to make a call to get the place details yourself.

```js
    onSelect = (_address, placeId) => {

        var request = {
            placeId: placeId
        };


        var placeRequest: Promise<google.maps.places.PlaceResult> = new Promise((resolve, reject) => {
            new google.maps.places.PlacesService(document.createElement('div')).getDetails(request, (place, status) => {
                if (status == google.maps.places.PlacesServiceStatus.OK) {
                    resolve(place);
                } else { reject() };
            });
        })
}
```

**Comment by nishtacular** [comment]
Thanks @Dashue, appreciate the tip! 🙏

**Comment by Dashue** [comment]
My pleasure :)

**Comment by lalspicesresearch** [comment]
@Dashue can you help me to implement your answer ?
var placeRequest: Promise<google.maps.places.PlaceResult> = new Promise((resolve, reject) => {
            new google.maps.places.PlacesService(document.createElement('div')).getDetails(request, (place, status) => {
                if (status == google.maps.places.PlacesServiceStatus.OK) {
                    resolve(place);
                } else { reject() };
            });
        })
Not able to implement it.

**Comment by Dashue** [comment]
@lalspicesresearch Please elaborate, what's not working, are you getting an error?
Also this is typescript code so will need a couple of packages installed. I wouldn't expect this piece of code to work just by itself.

Maybe open a new issues and add as much info and code as possible about your setup and situation and we can take it from there?
