### ISSUE TITLE
Unable to apply types filter

### ISSUE THREAD

**Issue by Dashue** [kenny-hibino/react-places-autocomplete#194]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
searchOptions aren't reflected in the query.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** 
specify searchOptions: { types: ['establishment'] }

**What is the expected behavior?**
Automcomplete should only contain establishments

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**

**Comment by kenny-hibino** [comment]
@Dashue It should be working. I just tested locally with the following code and all of the suggestions returned by Google Maps API are `establishment` types.

```js
const searchOptions = {
  types: ['establishment']
};

<PlacesAutocomplete
  value={this.state.address}
  onChange={this.handleChange}
  searchOptions={searchOptions}
>
  {/* custom render function here */
</PlacesAutocomplete>
```

Let me know if you are still seeing the issue!

**Comment by Dashue** [comment]
Thanks for your time. I'm more than likely doing something wrong.
What input did you give?
Could you include your query url captured from browser network traffic or fiddler?
When specifying establishments only, can you still lookup street addresses, i.e is it filtering out any results that aren't establishment or is it prioritizing establishments but still including other types?

Thanks for your help, I'll take a stab at it in a couple of hours. I'm sure we'll be able to figure it out and I'll let you know how it goes.

**Comment by Dashue** [comment]
Upgraded to 7.x from 6.1.3 and that solved it.

Thanks!

**Comment by TommyJackson85** [comment]
how do you restrict even more, like to 'cafe' 'bar' or 'library'? I'm getting errors when I include them and they are part of google's types in its api.
