### ISSUE TITLE
Google Maps JavaScript API library must be loaded

### ISSUE THREAD

**Issue by safeimuslim** [kenny-hibino/react-places-autocomplete#195]
Hi ,
My app ready on production, but sometimes i got error log from sentry, see bellow.

Error
Google Maps JavaScript API library must be loaded. See: https://github.com/kenny-hibino/react-places-autocomplete#load-google-library

**Comment by kenny-hibino** [comment]
@safeimuslim Unfortunately the library does not support async loading. (It's something I've been meaning to work on for a while now). 
Until we add support for asynchronous loading of Google library, you have to load Google Maps library before you mount a component that uses `PlacesAutocomplete`.

For example, in your `index.html`

```html
<!-- First load Google Maps library -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places"></script>
<!-- Then load your bundle file -->
<script src="bundle.js"></script>
```

**Comment by corysimmons** [comment]
This works for me:

```js
state = {
  gmapsLoaded: false,
}

initMap = () => {
  this.setState({
    gmapsLoaded: true,
  })
}

componentDidMount () {
  window.initMap = this.initMap
  const gmapScriptEl = document.createElement(`script`)
  gmapScriptEl.src = `https://maps.googleapis.com/maps/api/js?key=SECRET_EATING&libraries=places&callback=initMap`
  document.querySelector(`body`).insertAdjacentElement(`beforeend`, gmapScriptEl)
}

render () {
  return (
    <div>
      {this.state.gmapsLoaded && (
        <PlacesAutocomplete />
      )}
    </div>
  )
}
```

**Comment by kenny-hibino** [comment]
Closed via #199

**Comment by cesurk** [comment]
@corysimmons your solution was working in development but was breaking in our production instance.
Instead of adding a `componentDidMount` and a `initMap` function, I added a check to see if `window.google` was in scope and only then begin loading the Component that includes PlacesAutocomplete. See below:
`
{window.google && <SearchBox />}
`

**Comment by bpalmer661** [comment]
Hi could corysimmons are you or anybody else able to translate your solution to use in  a functional component?  that uses  react hooks?

**Comment by corysimmons** [comment]
@bpalmer661 Haven't tested this but this might work

```jsx
import { useState, useEffect } from 'react'

const SomeComponent = () => {
  const [gmapsLoaded, setGmapsLoaded] = useState(false)

  // This is how you do componentDidMount() with React hooks
  useEffect(() => {
    window.initMap = () => setGmapsLoaded(true)
    const gmapScriptEl = document.createElement(`script`)
    gmapScriptEl.src = `https://maps.googleapis.com/maps/api/js?key=SECRET_EATING&libraries=places&callback=initMap`
    document.querySelector(`body`).insertAdjacentElement(`beforeend`, gmapScriptEl)
  }, [])

  return (
    <div>
      {gmapsLoaded && (
        <PlacesAutocomplete />
      )}
    </div>
  )
}

export default SomeComponent
```

You might have to tinker with it, and it looks like this [might already be fixed](https://github.com/verejnedigital/verejne.digital/pull/141), and @cesurk [mentions](https://github.com/hibiken/react-places-autocomplete/issues/195#issuecomment-470568244) he needed to check if `window.google` existed in production, but hopefully this snippet can get you far enough to figure out the rest (if it doesn't outright work).

It might also not work just because Google seems to change how GMaps works every several months, completely breaking previous implementations. 🤷

**Comment by bpalmer661** [comment]
Thanks corysimmons I actually came up with the same solution myself , it works to solve it crashing though now the suggestions  found in the div below don't load and it always says "loading..." any ideas

 [ <div className="autocomplete-dropdown-container">
              {loading && <div>Loading...</div>}
              {suggestions.map(suggestion => {
                const className = suggestion.active
                  ? 'suggestion-item--active'
                  : 'suggestion-item';
                // inline style for demonstration purpose
                const style = suggestion.active
                  ? { backgroundColor: '#fafafa', cursor: 'pointer' }
                  : { backgroundColor: '#ffffff', cursor: 'pointer' };
                return (
                  
                  <div
                    {...getSuggestionItemProps(suggestion, {
                      className,
                      style,
                    })}
                  >
                    <span>{suggestion.description}</span>
                  </div>
                );
              })}
            </div>](url)

**Comment by Kathiriya-Savan** [comment]
I have to use the above functional solution but for some reason my PlacesAutocomplete it's not give me any suggestion How I solve this?
