### ISSUE TITLE
Changelog and github release for 7.0.x ?

### ISSUE THREAD

**Issue by moimael** [kenny-hibino/react-places-autocomplete#196]
Npm has release 7.0.1 but there is no changelog available and the release tag does not exist on github. Since it's a major version it would be great to know what breaking change we should expect and what is new :)

Thanks !

**Comment by kenny-hibino** [comment]
@moimael Thank you for reporting this! I added git tags to commits so it should be available now on Github 👍 

We don't have changelog for this project yet, but I wrote up a simple migration guide in wiki. Please take a look at this! https://github.com/kenny-hibino/react-places-autocomplete/wiki/Migration-Guide-(From-v6.x-to-v7.x)

Any feedback would be appreciated!!

**Comment by swrobel** [comment]
@kenny-hibino since I can't seem to edit the wiki, here's a corrected version of your v7 suggested code:

```jsx
<PlacesAutocomplete value={this.state.address} onChange={this.handleChange}>
  {({ getInputProps, suggestions, getSuggestionItemProps }) => (
    <div>
      <input {...getInputProps({ placeholder: 'Search Places...' })} />
      <div>
        {suggestions.map(suggestion => (
          <div {...getSuggestionItemProps(suggestion)}>
            {suggestion.description}
          </div>
        ))}
      </div>
    </div>
  )}
</PlacesAutocomplete>
```
