### ISSUE TITLE
Method onChange is being called when user clicks on a suggestion

### ISSUE THREAD

**Issue by maumont** [kenny-hibino/react-places-autocomplete#198]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The `onChange` method is called when the user clicks on a suggestion before the call to `onSelect`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
You can debug the [demo page](https://kenny-hibino.github.io/react-places-autocomplete/) or look directly into [the code](https://github.com/kenny-hibino/react-places-autocomplete/blob/master/src/PlacesAutocomplete.js#L315)

**What is the expected behavior?**
Based on the [README file](https://github.com/kenny-hibino/react-places-autocomplete#onselect):

>onSelect - You can pass a function that gets called **instead** of onChange function when the user hits the Enter key or clicks on a suggestion item.

I'm expecting that if the user clicks on an item **only** the `onSelect` method is being called. This was the old behavior in older versions (I just upgraded from `6.1.2` to `7.0.1`

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**

**Comment by inabeel** [comment]
I found similar problem in PlacesAutocomplete.js
On _this.handleInputOnBlur() function
line number: 234

_this.mousedownOnSuggestion property is not available, which causes it to execute clearSuggesstions() function
