### ISSUE TITLE
Passing arbitrary props to render method in v7

### ISSUE THREAD

**Issue by njbarrett** [kenny-hibino/react-places-autocomplete#204]
**Do you want to request a *feature* or report a *bug*?**
Bug/Question
**What is the current behavior?**
In v6 it seemed to be possible to pass arbitrary props to my render method through the inputProps prop. However with the changes in v7 I am not sure whether this is possible anymore.

```
<PlacesAutocomplete value={input.value} onChange={input.onChange} myOption={'hi!!'}>
    {({ getInputProps, getSuggestionItemProps, suggestions }) => {
        console.log(getInputProps());
        return (
            <div className="autocomplete-root">
                <TextField {...getInputProps()} errorText={touched && error} {...custom} />
                <div className="autocomplete-dropdown-container">
                    {suggestions.map(suggestion => (
                        <div {...getSuggestionItemProps(suggestion)}>
                            <span>{suggestion.description}</span>
                        </div>
                    ))}
                </div>
            </div>
        );
    }}
</PlacesAutocomplete>
```

I would like to know how my render method could access `myOption` . For example I need to pass through props to `TextField`.

**Comment by kenny-hibino** [comment]
@njbarrett Thank you for the question. 
You can pass arbitrary props to your input component via `getInputProps` function, and it's recommended that you pass to function rather than passing to the component directly. 
https://github.com/kenny-hibino/react-places-autocomplete#getinputprops
For the above example,

```js
<TextField {...getInputProps({ myOption: 'hi', errorText: (touched && error), ...custom  }) />
```

Hope this helps

**Comment by njbarrett** [comment]
Hi Kenny

Thank you for your response.
Your solution is OK if you are hardcoding a prop value into the render method, but I need to pass through a prop from higher up, however the `PlacesAutocomplete` component does not pass through all props to the children. I have made a change on my fork that passes through any other props: https://github.com/kenny-hibino/react-places-autocomplete/compare/master...njbarrett:master

If you feel this is wrong I would like to know why - otherwise if you think this is a good addition I can make a pull request.

Thanks
