### ISSUE TITLE
It is not selecting a place on click while it works perfectly from keyboard

### ISSUE THREAD

**Issue by khizar** [kenny-hibino/react-places-autocomplete#26]
I cant seem to make it work with a click on the place. It works perfectly if i navigate with the arrow keys and select with enter key. Even the live demo does not work with a click. Has anyone else faced this issue?

**Comment by kenny-hibino** [comment]
@khizar Thank you for this issue, this bug got introduced with the change I made last night. Will fix this ASAP!

**Comment by kenny-hibino** [comment]
Fixed #27  Shout out to @Ninjarab!
