### ISSUE TITLE
Demo link?

### ISSUE THREAD

**Issue by oyeanuj** [kenny-hibino/react-places-autocomplete#3]
Hi @kenny-hibino, thank you for putting out this library! I was wondering if you had any plans to put out a demo link, so one could test the functionality easily?

Also, was curious how it compares to react-geosuggest in your opinion?

Thank you!

**Comment by kenny-hibino** [comment]
@oyeanuj Thank you for opening this issue! I am open to the idea of making a demo link to demonstrate the functionality. I think I will be able to work on that next week. Would you be interested in helping me out with that? 

`react-geosuggest` is a more mature library and has been around for a while. But I wanted something more customizable, especially if you want to customize the autocomplete dropdown items. I believe my library has more flexibility when it comes to customizing the look of the UI. let me know if you are interested in contributing!

**Comment by kenny-hibino** [comment]
Thanks to @cburbank we have a demo site up and running on Github Pages. Please check it out [here](https://kenny-hibino.github.io/react-places-autocomplete/)

Major thanks to @cburbank !!
