### ISSUE TITLE
Move from inline styling to CSS based for easier overriding

### ISSUE THREAD

**Issue by ctrlaltdylan** [kenny-hibino/react-places-autocomplete#30]
Currently styling is set inline with `defaultStyles.js`, you can easily override the className of the autocomplete container but you cannot easily override it's styling because the styles are set inline.

**Proposal**

Move default styling to CSS or SCSS so the user can import the styling and override without touching Js.

**Comment by kenny-hibino** [comment]
@ctrlaltdylan YES! This has been a problem, thank you for opening this issue!! I like your proposal, and also let's look at how other component libraries (e.g react-select) are dealing with this kind of problem 👍

**Comment by ctrlaltdylan** [comment]
react-modal has a nice approach, it supports both JS driven styling and CSS overriding - https://github.com/reactjs/react-modal

If a `className` is given, then the `styles` are ignored. But you can pass either styles or className driven CSS. I think this one of the better approaches I've seen to support both.

**Comment by kenny-hibino** [comment]
@ctrlaltdylan I like that approach better! Making user to import our css file is a bit awkward. (I think that's some how some component libraries do it). Feel free to give it a try and submit a PR!
