### ISSUE TITLE
Switch autoComplete field to textArea

### ISSUE THREAD

**Issue by basiclaser** [kenny-hibino/react-places-autocomplete#32]
Hi there I'm trying to allow 2 lines worth of address to be visible by the user. 
Can i somehow use textArea?

**Comment by kenny-hibino** [comment]
@basiclaser Thank you for opening this issue. This feature is not currently in my project roadmap, but I'll keep this issue open in case other people request for the same feature 👍

**Comment by kenny-hibino** [comment]
Closing this since we haven't gotten similar feature requests in a long time.

**Comment by cchitsiang** [comment]
Hey @kenny-hibino, please have a look for PR #69, as currently we need this feature in place for our situation
