### ISSUE TITLE
Why select text then type, append to value but not remplace ? 

### ISSUE THREAD

**Issue by Steffi3rd** [kenny-hibino/react-places-autocomplete#40]
1 - I write : "Paris, Fra"
2 - I select all the text **"Paris, Fra"**
3 - I write : "London" 
4 - It gives me : "Paris, FraLondon"

---

Excepted

1 - I write : "Paris, Fra"
2 - I select all the text **"Paris, Fra"**
3 - I write : "London" 
4 - Removes "Paris, Fra"
5 - It gives me : "London"

Thanks!

**Comment by kenny-hibino** [comment]
Closed with 1be2036f45961b82bf55cd874209748bd6217296 👍
