### ISSUE TITLE
type "rfdlsfdmgjdflk" return Cannot read property 'lat' of null

### ISSUE THREAD

**Issue by Steffi3rd** [kenny-hibino/react-places-autocomplete#41]
When I type  "gdfg fdg ...G. DF GDFG FD", I have an real error.

> Cannot read property 'lat' of null

----

**Excepted :** 
STATUS : ZERO_RESULT

----

**Solution :** 
if result[0] exist define lat : results[0].geometry.location.lat(
else lat : 0

Something like that.

----

Inside this function : 
```
    geocoder.geocode({ address: address }, function (results, status) {
       if (status !== OK) {
         callback({ status: status }, null, results);
         return;
      }
      var latLng = {
        lat: results[0].geometry.location.lat(),
        lng: results[0].geometry.location.lng()
      };

      callback(null, latLng, results);
   });

```

**Comment by MHerszak** [comment]
We could reference this question/ request with #38?

**Comment by MHerszak** [comment]
You can actually also reference #20. Code splitting would be a good idea, especially for error handling.

**Comment by kenny-hibino** [comment]
Closing this issue
