### ISSUE TITLE
Integrations with Material UI and/or Redux Form

### ISSUE THREAD

**Issue by advance512** [kenny-hibino/react-places-autocomplete#43]
Hi there,

Great component. Any integration using Material UI's AutoComplete control?

What about support for being wrapped by redux-form?

Thanks!

**Comment by kenny-hibino** [comment]
@advance512 Thank you for opening this issue! We definitely need to add a better support for these popular libraries. I'm putting this on my todo list 👍

**Comment by ablbol** [comment]
Hi,
I was able to use this component with redux form.  Here is how I did it.  Please let me know if my work can be improved.

1) Create a component, I called it PlaceField that looks something like this:
```
import React from 'react';
import PlacesAutocomplete from 'react-places-autocomplete';


const AutocompleteItem = ({ formattedSuggestion }) => (
	<div>
		<strong>{ formattedSuggestion.mainText }</strong>{' '}
		<small>{ formattedSuggestion.secondaryText }</small>
	</div>
)

export const PlaceField = ({ input, label, meta: { touched, error }, ...rest }) => {
	const hasError = touched && error;
	const id = input.name;

	const classes={
		input: `form-control form-control-lg${hasError ? ' form-control-danger' : ''}`
	}

	return (
		<div className={`form-group${hasError ? ' has-danger' : ''}`}>
			<label className="form-control-label" htmlFor={id}>{label}</label>
			<PlacesAutocomplete 
				id={id}
				{...input}
				{...rest}
				typeAhead={false}
				inputName={input.name}
				autocompleteItem={AutocompleteItem}
				classNames={classes} />
			{hasError && <div className="form-control-feedback">{error}</div>}
		</div>
	);
}
```
2) In your form, place the Field component from Redux Form and make sure to use PlaceField component from above like this:
```
<Field
	name="address"
	placeholder="Enter your address"
	component={PlaceField}
	label="Address" />
```

**Comment by advance512** [comment]
Very nice! I'll have a look later at your solution this week.

**Comment by Aristona** [comment]
@kenny-hibino Any updates about this one?

**Comment by advance512** [comment]
I tried @ablbol's method and it seemed to work fine.
My issue now is that I need a multi-select, not single select. So I catch `onSelectChange` and update a Chip based Material UI component, which is wrapped as a Field, and it all works as expected.

**Comment by advance512** [comment]
I ended up using react-select to keep things more standard with other components.
Having a way to pass in an input control or a style would have been nice..

**Comment by parvinder19922** [comment]
Hi  ,
@ablbol
I have done this by putting input in inputProps

have a look 
return (
		<div className={`form-group${hasError ? ' has-danger' : ''}`}>
			<label className="form-control-label" htmlFor={id}>{label}</label>
			<PlacesAutocomplete 
				id={id}
				{...rest}
                               inputProps={input}
				typeAhead={false}
				inputName={input.name}
				autocompleteItem={AutocompleteItem}
				classNames={classes} />
			{hasError && <div className="form-control-feedback">{error}</div>}
		</div>
	);

**Comment by steph4nc** [comment]
> I ended up using react-select to keep things more standard with other components.
> Having a way to pass in an input control or a style would have been nice..

Hey @advance512, how did you manage to use react-places-autocomplete with react-select. Thanks

**Comment by advance512** [comment]
@steph4nc iirc, I extracted the places list from this control and injected it into the react-select component.
