### ISSUE TITLE
Safari doesn't work input symbols

### ISSUE THREAD

**Issue by dmfilipenko** [kenny-hibino/react-places-autocomplete#47]
Doesn't work in safari

**Comment by dmfilipenko** [comment]
component `PlacesAutocompleteWithTypeAhead` method `handleDefaultKey` event.key in safari return Unidentified https://github.com/facebook/react/issues/7897

**Comment by kenny-hibino** [comment]
@dmfilipenko Thank you so much for opening issue! I just confirmed the bug and also discovered that `typeAhead` doesn't work and very buggy in Firebox. I will change the README to say `typeAhead` is an experimental feature for the time being, and I will work on this bug fix ASAP. Again thank you for reporting!! 👍

**Comment by kenny-hibino** [comment]
I removed `typeAhead` feature in major version update to 5.0.0. Hopefully we can solve the browser incompatibility issue in the future and bring this feature back. Closing this for now.
