### ISSUE TITLE
Uncaught TypeError: Cannot read property 'suggestion' of undefined

### ISSUE THREAD

**Issue by squiles** [kenny-hibino/react-places-autocomplete#49]
Am I the only one that gets `Uncaught TypeError: Cannot read property 'suggestion' of undefined` when the down key is pressed?

**Comment by annaGo** [comment]
Nope.. Having the same issue.
It seems that 'handleSelect' sets the autocompleteItems which on the component state to [] after the selection and then onKeyDown is trying to access the selected item from that list.
Should be really simple fix.

**Comment by squiles** [comment]
Does anyone one have any news on this? 😄

**Comment by kenny-hibino** [comment]
Thank you for reporting this bug @squiles @annaGo !!! I just added a patch 👍
