### ISSUE TITLE
Support passing props to `input`

### ISSUE THREAD

**Issue by Andreyco** [kenny-hibino/react-places-autocomplete#51]
Either support passing props to underlying input, or allow user to provide component to render.

**Comment by kenny-hibino** [comment]
Currently the component takes a quite few props that are directly passed to input (`value`, `onChange`, `placeholder`, `inputName`, `inputId`, and also nested under `styles` and `classNames`) 

@Andreyco Did you have any specific prop in mind? 

Also, I'm thinking about combining these props to `inputProps` (object) in the next version release.

**Comment by Andreyco** [comment]
`onBlur` event is what I am looking for.

I will play with the lib locally and will try to add support for custom input element, which will allow flexibility & no similar feature requests like this :)

**Comment by kenny-hibino** [comment]
Closes via #60
