### ISSUE TITLE
Allow custom input component

### ISSUE THREAD

**Issue by cburbank** [kenny-hibino/react-places-autocomplete#6]
Hi @kenny-hibino ,

Have you considered allowing the choice of using a custom input component? That would be useful if you want to add autocomplete functionality to an existing input component (e.g., part of a different library). The _PlacesAutocomplete_ component could act as a wrapper, with the component you want to add the autocomplete functionality to as its child. So it would look like:

`<PlacesAutocomplete value={value} onChange={this.handleChange}><MyCustomInputComponent /></PlacesAutocomplete>`

If you think this feature would make sense to add, I'd be happy to take a shot and open a PR.

**Comment by kenny-hibino** [comment]
@cburbank Yes, that would be fantastic! The main purpose of this library should be an easy integration of React components with Google Maps Places API. I want the UIs to be customizable and the library to be flexible about it. I'm glad that you are willing to take a shot at it! Let me know if you need anything!

**Comment by kenny-hibino** [comment]
#9 Closes this issue. Thanks to @cburbank 😄
