### ISSUE TITLE
'type' in new inputProps, what does it do?

### ISSUE THREAD

**Issue by lolsheeplol** [kenny-hibino/react-places-autocomplete#61]
In the 5.0.0 update, there is a new prop called 'type' in inputProps

> const inputProps = {
    value,
    onChange,
    onBlur: () => {
      console.log('blur!')
    },
    **type: 'search',**
    placeholder: 'Search Places...',
    autoFocus: true,
  }

What does this prop do?  This is just a guess, but does it control the type of request the component uses (PlaceSearchRequest vs AutocompletionRequest)?  I'm looking to search for a specific type of place which isn't supported in AutocompletionRequest.

**Comment by kenny-hibino** [comment]
@lolsheeplol `inputProps` is for you to have full control of what gets passed to the input element. So with the `inputProps` with the above example, input element will look something like 

```js
<input type="search" placeholder="Search Places..." autofocus />
```
If you want to specify the type of place, please you [`options`](https://github.com/kenny-hibino/react-places-autocomplete#options) props which has  a`type` option 👍

**Comment by lolsheeplol** [comment]
Ah okay, I was asking specifically about the 'type' prop, but seeing your example makes it clear (it's passed through to the input element).  

About [options](https://github.com/kenny-hibino/react-places-autocomplete#options) though, I understand this library uses an AutocompletionRequest so the types array is limited to 4 supported types.  Say I wanted to filter results by `type=["airport"]`, which is only supported in the [PlaceSearchRequest](https://developers.google.com/maps/documentation/javascript/reference#PlaceSearchRequest), is that possible with this library?

**Comment by lolsheeplol** [comment]
Hi @kenny-hibino, sorry to bother you again but would the above request be in the scope of this library, or do you think it won't be supported going forward?

**Comment by kenny-hibino** [comment]
@lolsheeplol I need to look into this. Please feel free to fork this repo and experiment with `PlaceSearchRequest` API 👍

**Comment by kenny-hibino** [comment]
Closing this issue
