### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by soban-akram** [kenny-hibino/react-places-autocomplete#62]
I'm getting this warning,
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

printWarning	@	warning.js:36
warning	@	warning.js:60
get	@	React.js:95
162../defaultStyles	@	PlacesAutocomplete.js:352
s	@	_prelude.js:1
(anonymous)	@	_prelude.js:1
164../PlacesAutocomplete	@	index.js:8
s	@	_prelude.js:1
(anonymous)	@	_prelude.js:1
6.react	@	jobs_search_form.js:3
s	@	_prelude.js:1
(anonymous)	@	_prelude.js:1
(anonymous)	@	components.js:3
3../components/job	@	components.js:5
s	@	_prelude.js:1
(anonymous)	@	_prelude.js:1
(anonymous)	@	_stream_0.js:29
2../components	@	_stream_0.js:37
s	@	_prelude.js:1
e	@	_prelude.js:1
(anonymous)	@	_prelude.js:1

**Comment by kenny-hibino** [comment]
PR #63 Should resolve this 👍

**Comment by kenny-hibino** [comment]
Closed with PR #63
