### ISSUE TITLE
Any plans to add radius?

### ISSUE THREAD

**Issue by jrock17** [kenny-hibino/react-places-autocomplete#65]
This package looks great. Any plans to add radius filtering to limit results? I've seen other where you can pass in a location or country and limit results to a certain radius.

Thanks!

**Comment by kenny-hibino** [comment]
You can specify radius, locations, and type of locations through [`options` prop](https://github.com/kenny-hibino/react-places-autocomplete#options) 👍 
Hope this is what you are looking for!

**Comment by jrock17** [comment]
Boom! That's exactly what I was looking for.

Will the country param work too?

**Comment by kenny-hibino** [comment]
@jrock17 Yes! This is what you need

```javascript
const options = {
  componentRestrictions: {
    country: ['us', 'ca'] // Or if it's just one country you can have string (i.e. 'us')
  }
}

<PlacesAutocomplete inputProps={inputProps} options={options} />
```

Basically anything in Google's[ AutocompleteRequest specification](https://developers.google.com/maps/documentation/javascript/reference#AutocompletionRequest) will work 👍

**Comment by yalamber** [comment]
it's not working for me 
```
const placesOptions = {
    componentRestrictions: { 
      country: 'my'
    }
  }
<PlacesAutocomplete
              value={serviceAddress}
              onChange={handleChange}
              onSelect={handleSelect}
              options={placesOptions}
            />
```

**Comment by yalamber** [comment]
Ok seems like it should be searchOptions instead of options for props.
