### ISSUE TITLE
npm package version doesn't match repo tags or releases

### ISSUE THREAD

**Issue by lolsheeplol** [kenny-hibino/react-places-autocomplete#68]
Hi, 

I'm using version 4.1.3 of this library and `npm outdated` is showing there is a new version of 5.0.0.  I was wondering if you could provide a changelog or more detailed release notes on what has changed in this update as it is a sem-ver major update.  In this repo the last release version was 2.8.0, same with the tags so it's not really possible to do a proper diff and see if there are any breaking changes.  Any extra information on this latest update would be appreciated!

**Comment by kenny-hibino** [comment]
@lolsheeplol Thank you for reporting this! I will look into this. This project is using `commitizen`, `cz-conventional-changelog`, and `semantic-release` for the versioning. I noticed there's a mismatch between this repo on Github and on npm.

**Comment by lolsheeplol** [comment]
Any update on this?  I am still on a 4.x version of the lib and haven't updated to 5.x because I'm not sure what all the changes are.  A Changelog.md would be extremely helpful!

**Comment by lolsheeplol** [comment]
I can kind of guess what the changes are, just based on diffs for your commits to the README. 

It seems like the updates from 4.x to 5.x are briefly:
- `<PlacesAutocomplete />` now accepts a `inputProps` object rather than the exposed props [1](https://github.com/kenny-hibino/react-places-autocomplete/commit/e3b94c516ff248bfe4ec7fed296e462e7a333b05)
- `geocodeByAddress` method changed to a promise-like api using `.then` [2](https://github.com/kenny-hibino/react-places-autocomplete/commit/7763aef2931485c504def0c0628ed688def469de)
- A new `getLatLng`utility method to work with `geocodeByAddress` [3](https://github.com/kenny-hibino/react-places-autocomplete/commit/658701e8334351492314d82b7cdf639c64eb6999)

Are there any other changes I need to be aware of?

**Comment by kenny-hibino** [comment]
State Issue. Closing this.
