### ISSUE TITLE
`onEnterKeyDown` does not trigger when no autocomplete item exists.

### ISSUE THREAD

**Issue by SADA-Sam** [kenny-hibino/react-places-autocomplete#74]
`handleEnterKey` exists prematurely if `autocompleteItems` is empty.

It seems like this behavior was added in #53 as a response to an exception caused in `handleKeyDown` and it's subsequent call to `selectActiveItemAtIndex`. However `handleEnterKey` does not use the `selectActiveItemAtIndex` function so this check does not appear necessary, and prevents the `onEnterKeyDown` callback from triggering.

**Comment by kenny-hibino** [comment]
@SADA-Sam You are absolutely right!
