### ISSUE TITLE
No 'powered by google' logo?

### ISSUE THREAD

**Issue by hailwood** [kenny-hibino/react-places-autocomplete#75]
As noted by google here: 
https://developers.google.com/maps/documentation/javascript/places-autocomplete#fig1

> Note: When you display predictions from Place Autocomplete, you must include the '[powered by Google](https://developers.google.com/places/web-service/policies)' logo. This logo is included in the results list by default, as shown in the above example.

I've noted that this package does not seem to include the logo; Is this valid usage or should this package be showing the logo?

**Comment by hailwood** [comment]
ping for @kenny-hibino as we need to be all above board this is a dealbreaker for us; Any info?

**Comment by brotzky** [comment]
@hailwood we ended up manually adding in the logo with some simple CSS and a wrapping div. You're correct in pointing out the 'Powered by Google' is required.

**Comment by kenny-hibino** [comment]
@hailwood Thank you for creating this issue!! The library now supports this 👍

**Comment by mrynalrai** [comment]
@hibiken "powered by google" attribution is again no longer being displayed

**Comment by nizanjum** [comment]
how should I show "powered by google" in suggestion. @hibiken 
waiting for your reply

**Comment by mrynalrai** [comment]
@nizanjum if it helps, I added the image available https://developers.google.com/places/web-service/policies using css.
But I would also like to know the reason why it is no longer being displayed @hibiken
