### ISSUE TITLE
Is debounce supported?

### ISSUE THREAD

**Issue by nschurmann** [kenny-hibino/react-places-autocomplete#79]
Hello!, is debounce supported?, tryed to implement it with lodash but it seems that is tight coupled with the component.

**Comment by kenny-hibino** [comment]
@nschurmann  Thank you for opening this issue! 
Not currently, but we should add support for that 👍 I'll put that on my todo list. Feel free to submit a PR if you are interested.

**Comment by nschurmann** [comment]
Now is supported, please @kenny-hibino check my pull request.
