### ISSUE TITLE
Autocomplete doesn't work on mobile

### ISSUE THREAD

**Issue by ShayanJa** [kenny-hibino/react-places-autocomplete#87]
The places autocomplete doesn't work on my mobile phone, has anyone been able to use it on mobile? Excuse me if this issue has already been presented, I could not find it elsewhere

**Comment by kenny-hibino** [comment]
@ShayanJa Thank you for opening this issue. Could you provide which mobile browser you are using and which phone (Android/iPhone)?

**Comment by ShayanJa** [comment]
Yes I was using iPhone 6 on safari

**Comment by kenny-hibino** [comment]
What problems are you seeing? I'm on iPhone 6S and I tested with Safari and Chrome and both are working for me. Would you mind opening this page in your phone [Demo](https://kenny-hibino.github.io/react-places-autocomplete/)

**Comment by ShayanJa** [comment]
Wow that's so weird, it works. what settings are u using, on mine, the autocomplete bar doesn't come down

**Comment by kenny-hibino** [comment]
You can see the code for the Demo under `/Demo` directory in this repository 👍

**Comment by ShayanJa** [comment]
I integrated your demo src code into mine. exactly as written. it works fine on comp but not mobile. I don't know what is up, i'll try and figure it out. thanks

**Comment by kenny-hibino** [comment]
Closing this for now 👍
