### ISSUE TITLE
Uncaught Error: Missing parameter. You must specify input.

### ISSUE THREAD

**Issue by negomi** [kenny-hibino/react-places-autocomplete#88]
Steps to reproduce:
1. Type some letters into the field
2. Hold down the delete key to delete the letters
3. The error appears when all the letters have been deleted

Reproducible on the demo page:

<img width="1093" alt="screen shot 2017-06-07 at 2 45 23 pm" src="https://user-images.githubusercontent.com/3727684/26902946-055bcc90-4b90-11e7-80a5-4b38d78b218c.png">

**Comment by kenny-hibino** [comment]
@negomi Thank you for reporting this issue! Just added a patch, please install the latest version which includes the fix 👍

**Comment by negomi** [comment]
Perfect, thank you for the quick response! 😃
